Unrecoverable error state during Import	"Some customers report occasions, where an import shows an error message as in the attached screenshot.

The issue is, after clicking ""Back to export/import main page"", the import process is still stuck and it is impossible to start a new import.

The only known ""workaround"" so far is to restart iteraplan.



I cannot offer reproduction steps, as I was not able to reproduce the condition on my installation.

Code review however showed a method that could be responsible:

{{ImportProcessManager#extractStepResult(ImportStep)}}

If within the ""try"" section of the method an InterruptedException or ExecutionException happens, the observed unrecoverable error state appears (as verified by artificially causing such an exception).



Fix the method so the import process is reset/removed on such errors."		Bug	iteraplan PO	18/Apr/16 2:25 PM	22/Apr/16 9:21 AM					import									"19/Apr/16 10:51 AM;abo;Review Comments:

* Unify the exception handling in {{ImportProcessManager#extractStepResult(ImportStep)}} - e.g. use only 1 catch-block that catches _Exception_ since there may occur others, too.

* add a unit test, that covers the error condition"	"20/Apr/16 11:38 AM;sfe;I left the exception handling as is, since there are two possible error states here:

* An exception during execution of an import step happens. This causes exceptions when accessing the contents of the Future holding the result of the step. These are the exceptions caught in the two catch blocks in ""extractStepResult"", so an error message can be returned. This case is an explicitly considered outcome of executing an import step

* Another kind of exception not caught happens. This is unexpected and thus merits a different treatment. This case is caught farther out in the code in a wider security net, and produces different log statements, potentially helping with analysis. I have made the need for exception handling explicit by adding a ""throws"" statement and according javadoc."	"21/Apr/16 3:47 PM;abo;Review Comments:

* Java-Doc comment for unit-test should be in English but is in German.

* try-catch-block in {{ImportProcessManager.extractStepResult()}} does not add any benefit in contrast to catch in {{ImportFrontenedServiceImpl.updateMemBeanStatus()}}, except for maybe this line: {{ImportProcessStepResult.generalImportError();}} - please check, and hopefully remove the catch completely, replacing it with a throws in the method signature

* Please do not declare {{throws Exception}}, but instead use javadoc to inform a caller that it is necessary to catch {{RuntimeException}}."	"21/Apr/16 4:37 PM;sfe;If I don't catch the exceptions in ""extractStepResult"", the information which import step failed gets lost, ultimately resulting in the user getting a conflicting display: It looks as if iteraplan is still working on the current import, but additionally an error message is displayed.

I haven't found a quick solution to have the desired result (the failed step marked as failed) without the try-catch in ""extractStepResult""."																																																			
